monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::WARNING
                hub_id: 'Sentry\State\HubInterface'
            # this one acts like fingers_crossed
            sentry_breadcrumbs: # https://github.com/getsentry/sentry-php/pull/1199#issuecomment-1308936577
                type: service
                name: sentry_breadcrumbs
                id: Sentry\Monolog\BreadcrumbHandler
            sentry_buffer:
                type: buffer
                handler: 'sentry'
                level: !php/const Monolog\Logger::NOTICE
                channels: ["!sentry"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
