sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
    tracing:
        http_client:
            enabled: false

#        If you are using Monolog, you also need these additional configuration and services to log the errors correctly:
#        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
    register_error_listener: false

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException'
                    - 'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException'
                    - 'Symfony\Component\Routing\Exception\ResourceNotFoundException'
                    - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'

    # https://github.com/getsentry/sentry-php/pull/1199#issuecomment-1308936577
    Sentry\Monolog\BreadcrumbHandler:
        arguments:
            - '@Sentry\State\HubInterface'
            - !php/const Monolog\Logger::INFO
